### ISSUE TITLE
Not working on Android 8.1.0 Pixel 2 XL with plugin version 3.2.3

### ISSUE THREAD

**Issue by FranciZ** [NativeScript/nativescript-background-http#136] opened 2018-04-21 16:33 UTC
### Which platform(s) does your issue occur on?
- Android
- 8.1.0
- Pixel 2 XL

### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.4.2
- Cross-platform modules: 3.4.1
- Runtime(s): 3.4.2
- Plugin(s): 
```json
"devDependencies": {
    "@angular/compiler-cli": "~5.2.0",
    "@ngtools/webpack": "~1.9.4",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "codelyzer": "~4.0.2",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "1.5.0",
    "nativescript-dev-typescript": "~0.6.0",
    "nativescript-dev-webpack": "~0.9.1",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "~6.0.6",
    "tslint": "~5.8.0",
    "typescript": "~2.6.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }
```

### Please, tell us how to recreate the issue in as much detail as possible. 

When attempting upload I get the following error.

```json
{"eventName":"error","object":{"_observers":{"progress":[{}],"error":[{}],"complete":[{}]},"_session":{"_id":"image-upload"},"_id":"image-upload{1}","_description":"{ 'uploading': IMG-20180421-WA0003.jpg }","_upload":0,"_totalUpload":1,"_status":"error"}}
```

This must be related to issue https://github.com/NativeScript/nativescript-background-http/issues/124, but the 3.2.3 release does not fix it for me.

I can get it working by applying the fix as described here, https://github.com/NativeScript/nativescript-background-http/issues/124#issuecomment-377788306.

I've tried removing the `node_modules` and reinstalling. I've tried removing `tns platform remove android` and reinstalling. Does not help.

Copy pasting the code from that comment into `background-http.android.js` works.

If I replace:

```javascript
var displayNotificationProgress = typeof options.androidDisplayNotificationProgress === "boolean" ? options.androidDisplayNotificationProgress : true;
        if (displayNotificationProgress) {
            request.setNotificationConfig(new net.gotev.uploadservice.UploadNotificationConfig());
        }
```

with

```javascript
const displayNotificationProgress = typeof options.androidDisplayNotificationProgress === "boolean" ? options.androidDisplayNotificationProgress : true;
        if (displayNotificationProgress) {
            const channel = new android.app.NotificationChannel(application.android.packageName, application.android.packageName,
                android.app.NotificationManager.IMPORTANCE_LOW);
            const notificationManager = context.getSystemService(android.content.Context.NOTIFICATION_SERVICE)
            notificationManager.createNotificationChannel(channel);

            const uploadNotificationConfig = new net.gotev.uploadservice.UploadNotificationConfig();
            uploadNotificationConfig.setNotificationChannelId(application.android.packageName)
            request.setNotificationConfig(uploadNotificationConfig);
        }
```

on lines 128 and 181 than it works.

**Comment by lini** [comment] 2018-04-27 12:25
If you are still having trouble, try updating to the latest version of the plugin (3.2.5). It seems that you are still using an old version (with the old native dependency). If you can, try testing with one of the demo apps in this repository and see if the plugin works there. I tested them with a google device running android 8.1 and saw no issues.

**Comment by FranciZ** [comment] 2018-04-29 20:55
I tried updating to the latest version 3.2.5 with no results. I've removed the `node_modules` and removed the android platform multiple times with no success. Is there some other place I could have files from older versions? Each time I replace the code as mentioned above and then it works.

Let me know what information I can provide to help further.

**Comment by pauly815** [comment] 2018-05-04 00:49
I'm observing the same issue as FranciZ on 3.2.5.  I'm running TNS 3.4.2 on a Samsung S8 emulator with Android 8.0.  Only thing that worked for me was the fix from issue #24.

**Comment by pauly815** [comment] 2018-05-04 13:36
Unfortunately that fix does not work when I build and deploy to a Samsung S6 on Android 7.

**Comment by zbranzov** [comment] 2018-05-16 13:07
Hi,
Can someone send an app so we can reproduce the issue?
Currently, using the demo-angular sample from the repository we are unable to reproduce your case. We are testing on Nexus 5x and Pixel 2 (both Android 8.1) and latest plugin version.

**Comment by pauly815** [comment] 2018-05-21 02:25
I am no longer having the issue when upgrading to version 3.2.6.

**Comment by radeva** [comment] 2018-05-24 08:51
Closing since the issue seems to be solved.

**Closed by radeva** 2018-05-24 08:51 UTC
Labels: bug, needs more info, os: android
