### ISSUE TITLE
Error calling module function: background-http 

### ISSUE THREAD

**Issue by DavidHLau** [NativeScript/nativescript-background-http#109] opened 2018-02-13 00:56 UTC
**Android platform**

**Plugin**: nativescript-background-http    **Latest version**: 3.1.0

**Sample Code**:

var bghttpModule = require("nativescript-background-http");

_______________________________________________

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.ImageUpload/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error calling module function 

Error calling module function 

TypeError: Cannot read property 'extend' of undefined
File: "file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/nativescript-background-http/background-http.js, line: 7, column: 77

StackTrace: 
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/nativescript-background-http/background-http.js', line: 7, column: 78
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/home/home-page.js', line: 26, column: 20
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'_loop_1', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 60, column: 22
Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 68, column: 23
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 82, column: 27
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 108, column: 29
Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25

TypeError: Cannot read property 'extend' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/nativescript-background-http/background-http.js', line: 7, column: 78
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/home/home-page.js', line: 26, column: 20
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'_loop_1', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 60, column: 22
Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 68, column: 23
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 82, column: 27
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 108, column: 29
Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25

TypeError: Cannot read property 'extend' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/nativescript-background-http/background-http.js', line: 7, column: 78
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/home/home-page.js', line: 26, column: 20
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'_loop_1', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 60, column: 22
Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 68, column: 23
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 82, column: 27
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 108, column: 29
Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25

at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3003)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064)
at android.app.ActivityThread.-wrap14(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6816)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error calling module function 

Error calling module function 

TypeError: Cannot read property 'extend' of undefined
File: "file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/nativescript-background-http/background-http.js, line: 7, column: 77

StackTrace: 
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/nativescript-background-http/background-http.js', line: 7, column: 78
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/home/home-page.js', line: 26, column: 20
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'_loop_1', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 60, column: 22
Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 68, column: 23
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 82, column: 27
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 108, column: 29
Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25

TypeError: Cannot read property 'extend' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/nativescript-background-http/background-http.js', line: 7, column: 78
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/home/home-page.js', line: 26, column: 20
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'_loop_1', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 60, column: 22
Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 68, column: 23
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 82, column: 27
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 108, column: 29
Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25

TypeError: Cannot read property 'extend' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/nativescript-background-http/background-http.js', line: 7, column: 78
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/home/home-page.js', line: 26, column: 20
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'_loop_1', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 60, column: 22
Frame: function:'global.loadModule', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 68, column: 23
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 82, column: 27
Frame: function:'', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 108, column: 29
Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.ImageUpload/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25

at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
at com.tns.Runtime.callJSMethod(Runtime.java:957)
at com.tns.Runtime.callJSMethod(Runtime.java:941)
at com.tns.Runtime.callJSMethod(Runtime.java:933)
at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
at android.app.Activity.performCreate(Activity.java:6977)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
... 9 more

**Comment by Icer2000** [comment] 2018-02-14 10:51
Could be a caching issue.
Have you tried?
rm -rf platforms/android, tns platform add android

**Comment by lini** [comment] 2018-02-23 15:21
Duplicate of #96
Removing platforms directory and building the app will solve this.

**Closed by lini** 2018-02-23 15:21 UTC
