### ISSUE TITLE
Doesn't work with Android API 26

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/nativescript-background-http#99] opened 2018-01-21 21:50 UTC
I had to set API level to 25 so that it works. No problem with iOS.

**Comment by NickIliev** [comment] 2018-01-24 13:52
@erkanarslan please provide more information on what the issue is - is your application throwing an error (if yes please post the stack trace) and what is the specific code used to reproduce the issue.

**Comment by erkanarslan** [comment] 2018-01-24 16:58
Background http plugin or internal Android libraries show a notification in the Notification Center when uploading a file. Problem is related to that. I cannot remember it correctly but it was saying that a channel for notification is not set or incorrectly set. I learned that in API 26, you can group/classify notifications by channels. I was testing that on an emulator with Android 8.

**Comment by NickIliev** [comment] 2018-01-25 11:10
@erkanarslan thanks for reporting this issue - as far as I see it is identical to [this one](https://github.com/NativeScript/nativescript-background-http/issues/85) which I have logged as a bug.
The plugins team will investigate and log any info in the linked issue.

Closing this one as a duplicate to [https://github.com/NativeScript/nativescript-background-http/issues/85](https://github.com/NativeScript/nativescript-background-http/issues/85)

**Closed by NickIliev** 2018-01-25 11:10 UTC
Labels: os: android, question
